# Book settings
title: Equity Research Associate
author: Riku Driscoll
logo: 'logo.png'

latex:
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
